apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-helloworld
  name: nginx-helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-helloworld
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-helloworld
    spec:
      containers:
      - image: rakpw/nginx-helloworld:v0.1.33
        name: nginx-helloworld
        resources: {}
status: {}
