name: Docker Build, Push and Update Deployment

on:
  push:
    tags:
      - 'v*'  # Push events for tags starting with 'v'

jobs:
  build-push-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      id: build-push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: rakpw/nginx-helloworld:${{ github.ref_name }}

    - name: Update image tag in deployment.yaml
      run: |
        IMAGE_TAG=${{ github.ref_name }}
        sed -i "s|rakpw/nginx-helloworld:v[0-9]\+\.[0-9]\+\.[0-9]\+|rakpw/nginx-helloworld:${IMAGE_TAG}|g" fleet/deployment.yaml

    - name: Create pull request
      id: cpr
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.PAT }}
        branch: update-image-tag-${{ github.ref_name }}
        title: Update image tag to ${{ github.ref_name }}
        body: This pull request updates the image tag to ${{ github.ref_name }}.
        base: main

    - name: Enable Pull Request Automerge
      if: ${{ steps.cpr.outputs.pull-request-number }}
      uses: peter-evans/enable-pull-request-automerge@v3
      with:
        token: ${{ secrets.PAT }}
        pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
        merge-method: squash

