name: Docker Build, Push and Update Deployment

on:
  push:
    tags:
      - 'v*'  # Push events for tags starting with 'v'

jobs:
  build-push-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      id: build-push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: rakpw/nginx-helloworld:${{ github.ref_name }}

    - name: Update image tag in deployment.yaml
      run: |
        IMAGE_TAG=${{ github.ref_name }}
        sed -i "s|rakpw/nginx-helloworld:[0-9]\+\.[0-9]\+\.[0-9]\+|rakpw/nginx-helloworld:${IMAGE_TAG}|g" fleet/deployment.yaml

    - name: Commit and push changes
      run: |
        IMAGE_TAG=${{ github.ref_name }}
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git checkout -b update-image-tag
        git add fleet/deployment.yaml
        git commit -m "Update image tag to ${IMAGE_TAG}"
        git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/rak-phillip/nginx-hello-world.git
        git push origin update-image-tag

    - name: Create pull request
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const IMAGE_TAG = ${{ github.ref_name }}
          const title = `Update image tag to ${IMAGE_TAG}`
          const body = `This pull request updates the image tag to ${IMAGE_TAG}.`
          const head = 'update-image-tag'
          const base = 'main'
          const pullRequest = await github.rest.pulls.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title,
            body,
            head,
            base
          })
          console.log(`Created pull request #${pullRequest.data.number}`)
